from pathlib import Path
BASE_DIR = Path(__file__).resolve().parents[2]

# PREFERENCE GENERATOR MODELS
SFT_MODEL = str(BASE_DIR / "checkpoints/sft/merged_model")
TOKENIZER_MODEL_PREFERENCE_GENERATOR = SFT_MODEL

# PREFERENCE GENERATION - DPO DATASET PATH
DPO_DS = str(BASE_DIR / "data/preferences/dpo_dataset.jsonl")

# PREFERENCE GENERATION HYPERPARAMETERS
N_CANDIDATES = 2 
TEMPERATURE = 0.7
TOP_P = 0.95

# SANDBOX CONFIG
SANDBOX_IMAGE_NAME = "codealign-executor:latest"
EXECUTION_TIMEOUT = 2

# COMPOSITE REWARD PARAMETERS
W_EXEC = 1.0 
W_COMPLEXITY = 0.1 
W_LINT = 0.2 

# PREFERENCE GENERATION REPORT
DPO_REPORT = "data/preferences/dpo_report.jsonl"

# WANDB CONFIG
WANDB_RUN_NAME = "phase3-preference-generation"