# PREFERENCE GENERATOR MODELS
SFT_MODEL = "checkpoints/sft/final_model"
TOKENIZER_MODEL_PREFERENCE_GENERATOR = "Qwen/Qwen2.5-Coder-7B-Instruct"

# PREFERENCE GENERATION - DPO DATASET PATH
DPO_DS = "data/preferences/dpo_dataset.jsonl"

# PREFERENCE GENERATION HYPERPARAMETERS
N_CANDIDATES = 2 # o 4??
TEMPERATURE = 0.7 # entre 0.6 y 0.8
TOP_P = 0.95

# SANDBOX CONFIG
SANDBOX_IMAGE_NAME = "codealign-executor:latest"
EXECUTION_TIMEOUT = 2

# COMPOSITE REWARD PARAMETERS
W_EXEC = 1.0 
W_COMPLEXITY = 0.1 
W_LINT = 0.2 